import { type Product } from './types';

export const products: Product[] = [
  {
    id: 'drivetrain-set',
    name: '12-Speed Drivetrain Set',
    category: 'parts',
    price: 450,
    description: 'Complete 12-speed drivetrain group set including shifter, derailleur, cassette, and chain. Perfect for an upgrade or new build.',
    images: ['https://images.unsplash.com/photo-1738918935719-398c6cc3c51a?w=900&auto=format&fit=crop', 'https://placehold.co/600x400.png'],
    imageHints: ['bicycle drivetrain'],
    specifications: {
      Compatibility: 'Most modern bike frames',
      Cassette: '11-50T',
      'Rear Derailleur': 'Long cage, clutch-equipped',
      Material: 'Steel and Aluminum',
    },
  },
  {
    id: 'hydraulic-brakes',
    name: 'Hydraulic Disc Brake Kit',
    category: 'parts',
    price: 180,
    description: 'Powerful and reliable stopping power. This kit includes front and rear pre-bled hydraulic disc brakes, levers, and rotors.',
    images: ['https://images.unsplash.com/photo-1744302570694-3f8949445c2b?w=900&auto=format&fit=crop', 'https://placehold.co/600x400.png'],
    imageHints: ['disc brakes'],
    specifications: {
      'Rotor Size': '160mm (front & rear)',
      'Brake Fluid': 'Mineral Oil',
      Pistons: '2 per caliper',
      Includes: 'Levers, calipers, hoses, rotors',
    },
  },
  {
    id: 'eco-100-dulux',
    name: 'ECO 100 Dulux',
    category: 'bikes',
    price: 22499,
    description: 'A reliable and efficient motorbike for everyday use.',
    images: ['https://images.unsplash.com/photo-1685478565312-2ab3cb198d8b?q=80&w=2671&auto=format&fit=crop', 'https://placehold.co/600x400.png'],
    imageHints: ['motorbike'],
    specifications: {
      'Engine': '100cc',
      'Power': '12.5hp',
      'Torque': '12.5Nm',
      'Top Speed': '120km/h',
      'Weight': '120kg',
    },
  },
  {
    id: 'eco-150',
    name: 'ECO 150',
    category: 'bikes',
    price: 31899,
    description: 'A powerful and stylish motorbike for the modern rider.',
    images: ['https://images.unsplash.com/photo-1648300119079-792d50efce72?q=80&w=2670&auto=format&fit=crop', 'https://placehold.co/600x400.png'],
    imageHints: ['motorbike'],
    specifications: {
      'Engine': '150cc',
      'Power': '12.5hp',
      'Torque': '12.5Nm',
      'Top Speed': '120km/h',
      'Weight': '120kg',
    },
  },
  {
    id: 'eco-150tr-trail',
    name: 'ECO 150TR Trail',
    category: 'bikes',
    price: 22199,
    description: 'A rugged and durable motorbike built for the trail.',
    images: ['https://images.unsplash.com/photo-1657645157714-36cda0e30794?q=80&w=1334&auto=format&fit=crop', 'https://placehold.co/600x400.png'],
    imageHints: ['trail motorbike'],
    specifications: {
      'Engine': '150cc',
      'Power': '12.5hp',
      'Torque': '12.5Nm',
      'Top Speed': '120km/h',
      'Weight': '120kg',
    },
  },
  {
    id: 'xpluse-350',
    name: 'XPluse 350',
    category: 'bikes',
    price: 41200,
    description: 'The ultimate adventure motorbike, ready for any journey.',
    images: ['https://images.unsplash.com/photo-1564347288823-dcdd367f3847?w=900&auto=format&fit=crop', 'https://placehold.co/600x400.png'],
    imageHints: ['adventure motorbike'],
    specifications: {
      'Engine': '350cc',
      'Power': '12.5hp',
      'Torque': '12.5Nm',
      'Top Speed': '120km/h',
      'Weight': '120kg',
    },
  },
];
