import { type Product } from './types';

export const products: Product[] = [
  {
    id: 'mtb-pro',
    name: 'Mountain Pro Bike',
    category: 'bikes',
    price: 2500,
    description: 'Conquer any trail with the Mountain Pro. Featuring a lightweight aluminum frame, full suspension, and hydraulic disc brakes for ultimate control.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    imageHints: ['mountain bike', 'bike suspension', 'bike brakes'],
    specifications: {
      Frame: 'ALUXX SL-Grade Aluminum',
      Fork: 'RockShox Recon Silver RL, 130mm',
      Drivetrain: 'SRAM SX Eagle, 1x12',
      Brakes: 'Shimano MT420 hydraulic, 4-piston',
      Weight: '13.5 kg',
    },
  },
  {
    id: 'road-racer-x',
    name: 'Road Racer X',
    category: 'bikes',
    price: 3200,
    description: 'Experience pure speed. The Road Racer X is built with an advanced carbon composite frame for an incredibly light and stiff ride.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    imageHints: ['road bike', 'carbon frame', 'racing bicycle'],
    specifications: {
      Frame: 'Advanced-Grade Composite',
      Fork: 'Advanced-Grade Composite, full-composite OverDrive steerer',
      Drivetrain: 'Shimano Ultegra, 2x11',
      Brakes: 'Shimano Ultegra hydraulic',
      Weight: '7.8 kg',
    },
  },
  {
    id: 'urban-commuter',
    name: 'Urban Commuter Bike',
    category: 'bikes',
    price: 850,
    description: 'Navigate the city with ease. Our Urban Commuter offers a comfortable ride, integrated lights, and a rear rack for your essentials.',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    imageHints: ['commuter bike', 'city bicycle'],
    specifications: {
      Frame: 'Lightweight Alloy',
      Fork: 'High-tensile steel',
      Drivetrain: 'Shimano Altus, 1x8',
      Brakes: 'Tektro mechanical disc',
      Weight: '12.1 kg',
    },
  },
  {
    id: 'drivetrain-set',
    name: '12-Speed Drivetrain Set',
    category: 'parts',
    price: 450,
    description: 'Complete 12-speed drivetrain group set including shifter, derailleur, cassette, and chain. Perfect for an upgrade or new build.',
    images: ['https://placehold.co/600x400.png'],
    imageHints: ['bicycle drivetrain'],
    specifications: {
      Compatibility: 'Most modern mountain bike frames',
      Cassette: '11-50T',
      'Rear Derailleur': 'Long cage, clutch-equipped',
      Material: 'Steel and Aluminum',
    },
  },
  {
    id: 'hydraulic-brakes',
    name: 'Hydraulic Disc Brake Kit',
    category: 'parts',
    price: 180,
    description: 'Powerful and reliable stopping power. This kit includes front and rear pre-bled hydraulic disc brakes, levers, and rotors.',
    images: ['https://placehold.co/600x400.png'],
    imageHints: ['disc brakes'],
    specifications: {
      'Rotor Size': '160mm (front & rear)',
      'Brake Fluid': 'Mineral Oil',
      Pistons: '2 per caliper',
      Includes: 'Levers, calipers, hoses, rotors',
    },
  },
];
